### ISSUE TITLE
Update serialport version

### ISSUE THREAD

**Issue by mrstegeman** [AlanDThiessen/cm11a-js#1]
It would be great to update serialport for Node 12 support.

**Comment by AlanDThiessen** [comment]
Upgraded to serialport@8.0.6 in commit d76cc31.

**Comment by AlanDThiessen** [comment]
Updates were tested using the test script on a Raspberry Pi running Mozilla Webthings Gateway v0.10.0.

**Comment by mrstegeman** [comment]
Great! This should allow the X10 adapter to run on newer Node versions. I'm hoping to move the gateway off of Node 8 soon, since it's EOL.
